/** @format */

import Head from "next/head";
import Layout from "../components/Layout";
import {
  Container,
  Row,
  Col,
  Text,
  Grid,
  Card,
  Checkbox,
  Input,
  Navbar,
  Dropdown,
  Button,
  Collapse,
  Image,
  Spacer,
  Switch,
  changeTheme,
  useTheme,
} from "@nextui-org/react";
import { Hero } from "../components/Hero";
import Bootstrap1 from "../components/Bootstrap1";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <div>
          <Grid.Container>
          <Bootstrap1 direccion={"img/laperla.jpg"} titulo={"tu mama"} contedido={"tu vieja"}/> 
          <Hero clase={"hero1"} titulo={"centro1"} desc={"klajsdf,basdfjaadf"}/>
          <Hero clase={"hero1"} titulo={"centro1"} desc={"klajsdf,basdfjaadf"}/>
          <Hero clase={"hero1"} titulo={"centro1"} desc={"klajsdf,basdfjaadf"}/>
          <Hero clase={"hero1"} titulo={"centro1"} desc={"klajsdf,basdfjaadf"}/>
          </Grid.Container>
        </div>
      </Layout>
    </div>
  );
}
