/** @format */

import Head from "next/head";
import Layout from "../components/Layout";
import {
  Container,
  Row,
  Col,
  Text,
  Grid,
  Card,
  Checkbox,
  Input,
  Navbar,
  Dropdown,
  Button,
  Collapse,
  Image,
  Spacer,
  Switch,
  changeTheme,
  useTheme,
} from "@nextui-org/react";
import { Hero } from "../components/Hero";
import Bootstrap1 from "../components/Bootstrap1";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Historia</title>
        <meta name='description' content='Generated by create next app' />
        <meta charset="UTF-8" />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Grid.Container css={{ mt: "50px" }} justify='center'>
          <Grid justify="center" xs={12}>
            <Text justify="center" h2 >
              Centros clandestinos de detencion
            </Text>
          </Grid>
          </Grid.Container>
          <Grid.Container>
          <Grid xs={4}></Grid>
          <Grid className='subrayado' xs={4}></Grid>
          <Grid xs={4}></Grid>
          </Grid.Container>
          <Grid.Container css={{ mt: "50px" }}>
            <Bootstrap1
              direccion={"img/centro-index.jpg"}
              titulo={"¿QUÉ SON?"}
              contedido={
                "Fueron aquellas instalaciones ilegales, y secretas empleadas por las Fuerzas Armadas, de Seguridad y policiales para ejecutar el plan de desaparición de personas llevado a cabo en la Argentina durante la dictadura militar autodenominada. Estos centros se crearon debido a la reclusión ilegal del terrorismo de Estado en Argentina desde fines de 1974 y especialmente, a partir de la aplicación plena del plan sistemático de exterminio ejecutado por la última dictadura cívicomilitar en todo el territorio nacional, entre el 24 de marzo de 1976 y el 10 de diciembre de 1983."
              }
            />
          </Grid.Container>
        <Grid.Container>
          <Grid alignItems='center' justify='center' xs={12} md={12}>
            <Text h5>¿CÓMO ERAN ESTOS CENTROS?</Text>
          </Grid>
          <Grid xs={5}></Grid>
          <Grid xs={2} className='subrayado'>
            <Grid xs={5}></Grid>
          </Grid>
        </Grid.Container>
        <Grid.Container css={{ mt: "50px", mb: "50px" }}>
          <Grid alignItems='center' css={{ p: "10%" }} xs={12} md={7}>
            <Text>
              Todos los CCD contaban con una o más salas de torturas, amplios
              espacios para mantener a los desaparecidos siempre en condiciones
              de gran precariedad, y un centro de viviendas para los
              torturadores y guardias. Casi todos tenían algún tipo de servicio
              médico. Pero a su vez estos centros se dividieron o clasificaron
              en 2 tipos, según las FFAA:
            </Text>
          </Grid>
          <Grid xs={12} md={5}>
            <Card css={{ mw: "370px" }}>
              <Card.Header>
                <Text b>Tipos</Text>
              </Card.Header>
              <Card.Divider />
              <Card.Body css={{ py: "$10" }}>
                <ul>
                  <li>
                    - Lugar Definitivo (LD): tenían una organización más estable
                    y estaban preparados para alojar, torturar y asesinar a
                    grandes cantidades de detenidos.
                  </li>
                  <li>
                    - Lugar Transitorio (LT): tenían una infraestructura
                    precaria y estaban destinados a funcionar como un primer
                    lugar de alojamiento de los detenidos-desaparecidos.
                  </li>
                </ul>
              </Card.Body>
              <Card.Divider />
            </Card>
          </Grid>
        </Grid.Container>
        <Grid.Container>
          <Hero
            clase={"hero1"}
            titulo={"ESMA"}
            desc={"Avenida del Libertador 8151, CABA."}
            href={"./centro1"}
          />
          <Hero
            clase={"hero2"}
            titulo={"CLUB ATLÉTICO"}
            desc={"Avenida Paseo Colón 1266, CABA."}
            href={"./centro2"}
          />
          <Hero
            clase={"hero3"}
            titulo={"EL INFIERNO DE AVELLANEDA"}
            desc={"12 de Octubre, Avellaneda, Provincia de Buenos Aires"}
            href={"./centro3"}
          />
          <Hero
            clase={"hero4"}
            titulo={"EL OLIMPO"}
            desc={"Vélez Sarsfield entre las calles Olivera, Ramón Falcón, Lacarra, Fernández y Rafaela"}
            href={"./centro4"}
          />
          <Hero
            clase={"hero5"}
            titulo={"QUINTA DE FUNES"}
            desc={"Ruta 9 y, San José, Funes, Santa Fe"}
            href={"./centro5"}
          />
          <Hero
            clase={"hero6"}
            titulo={"BATALLÓN DE ARSENALES"}
            desc={"Monte Chingolo (Quilmes y Lanús), Santa Fe."}
            href={"./centro6"}
          />
        </Grid.Container>
      </Layout>
    </div>
  );
}
